version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-node8-alpha
    machine: java: version: openjdk8
    environment:
        JVM_OPTS: -Xmx3200m
        ANDROID_HOME: /usr/local/android-sdk-linux
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Static code analyzers
          command: ./gradlew detektCheck checkstyle pmd lintProductionRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Unit Tests
          command: ./gradlew testProductionReleaseUnitTest testProductionDebugUnitTest
      - store_test_results:
          path: app/build/test-results